# Generated by Django 5.2.9 on 2026-06-03 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinlist',
            name='shoppingcart',
        ),
        migrations.AddField(
            model_name='shoppinlist',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shoppings_list', to='shop.shoppingcart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppinlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
