# Generated by Django 5.2.9 on 2026-06-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shoppinlist_shoppingcart_shoppinlist_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='address_null', max_length=250),
        ),
    ]
